vich_uploader:
    db_driver: orm

    mappings:
        postImg:
            uri_prefix: '%app.path.upload_img%'
            upload_destination: '%kernel.project_dir%/public/upload/img'
            namer: Vich\UploaderBundle\Naming\UniqidNamer
