vich_uploader:
    db_driver: orm

    mappings:
        post_image:
            uri_prefix: '%app.path.upload_img%'
            upload_destination: '%kernel.project_dir%/public/upload/img'
            namer: Vich\UploaderBundle\Naming\UniqidNamer

        cat_img:
            uri_prefix: '%app.path.upload_img%'
            upload_destination: '%kernel.project_dir%/public/upload/img'
            namer: Vich\UploaderBundle\Naming\UniqidNamer
