<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerApRO6r0\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerApRO6r0/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerApRO6r0.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerApRO6r0\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerApRO6r0\App_KernelDevDebugContainer([
    'container.build_hash' => 'ApRO6r0',
    'container.build_id' => 'a5a32fb3',
    'container.build_time' => 1633525041,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerApRO6r0');
