<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerGKhbwex\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerGKhbwex/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerGKhbwex.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerGKhbwex\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerGKhbwex\App_KernelDevDebugContainer([
    'container.build_hash' => 'GKhbwex',
    'container.build_id' => '3789a41a',
    'container.build_time' => 1632488455,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerGKhbwex');
